version: "2"
services:
  web:
    build:
      context: .
      args:
        NEXTAUTH_URL: $$NEXTAUTH_URL
    command: sh -c "/wait && yarn prisma migrate deploy && yarn start"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://root:wGJT3Psz@database:3306/cis_capstone_wi23
      - NEXTAUTH_SECRET=PGpzmn9Y6J+tD4BGTuY+PGjrk6rB1U5eneDSNvxbQaM=
      - NEXTAUTH_URL=http://course-scheduling.svsu.edu
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      course-scheduling-internal:
        ipv4_address: 192.168.120.21
    restart: always

  webproxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      course-scheduling-internal:
        ipv4_address: 192.168.120.20
    restart: always

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "wGJT3Psz"
      MYSQL_DATABASE: "cis_capstone_wi23"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      course-scheduling-internal:
        ipv4_address: 192.168.120.22
    restart: always

networks:
  course-scheduling-internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.120.0/24"
