version: "2"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://root:password@localhost/capstone
      NEXTAUTH_SECRET: PGpzmn9Y6J+tD4BGTuY+PGjrk6rB1U5eneDSNvxbQaM=
      NEXTAUTH_URL: http://localhost:3000

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
